### ISSUE TITLE
imod .coords seems to have an offset in napari

### ISSUE THREAD

**Issue by thorstenwagner** [MPI-Dortmund/napari-boxmanager#34]
According the mailing list:

> Hello Thorsten,
> 
> I mentioned before that coordinates visualised in Napari do not seem to match the visualisation in imod. IE filaments manually picked in imod appear to be offset in Napari.
> 
> I fixed this by applying an origin correction based on the origin that is displayed in the header of the tomograms from imod. In my case I have to adjust 15px in X and 16 in Y, based on a pixel size of 7.0184A, which shifts everything into place. Possibly Napari doesn't account for the origin when displaying coordinates?
> 
> Best regards,
> 
> Charlie

**Comment by GavinR1** [comment]
I tried to reproduce this issue with the following method which we also use in the lab for tracing filaments manually:

1. Open tomo in imod
2. change mode to model, change object type to open
3. Place points at ends of filament
4. save mod file
5. use AddModPts to fill in picks for filament
6. visualize mod file in imod
![Screenshot 2023-06-19 at 11 06 34](https://github.com/MPI-Dortmund/napari-boxmanager/assets/68530156/5c75b576-ca97-4181-a47d-3e6ca45ad4f4)
7. open tomogram in napari
8. use Model2Point to convert mod file to coords file (only input and output provided, no options)
9. visualize coords file in napari using napari-boxmanager
<img width="2546" alt="Screenshot 2023-06-19 at 11 35 22" src="https://github.com/MPI-Dortmund/napari-boxmanager/assets/68530156/67507736-0729-4c2a-a07d-c9d2bf942168">

Based on this I can't seem to reproduce the issue. I checked, the X,Y origin of this tomo is 0,0 as is true for all of my experimental tomograms of different datasets/samples.

Can you provide an example of a tomo where the origin is not 0,0 and how this happens?

**Comment by thorstenwagner** [comment]
hm, I will close this until someone brings this up again.
