### ISSUE TITLE
Update explicit dependencies

### ISSUE THREAD

**Issue by goanpeca** [MPI-Dortmund/napari-boxmanager#36]
Hi @thorstenwagner 👋🏼 

In working on https://github.com/conda-forge/napari-boxmanager-feedstock/pull/5 I noticed that some packages that are being used explicitly (`import package`) are not being listed as dependencies of the package. It still works as napari is bringing these deps, but that may not be always the case, plus we should list all dependencies we rely on explicitly.

The packages are:
    - [qtpy](https://github.com/search?q=repo%3AMPI-Dortmund%2Fnapari-boxmanager%20qtpy&type=code)
    - [scipy](https://github.com/search?q=repo%3AMPI-Dortmund%2Fnapari-boxmanager%20scipy&type=code)
    - [tifffile](https://github.com/search?q=repo%3AMPI-Dortmund%2Fnapari-boxmanager%20tifffile&type=code)
    - [tqdm](https://github.com/search?q=repo%3AMPI-Dortmund%2Fnapari-boxmanager%20tqdm&type=code)
    
Could you update this for a future release?

Thanks 🙌🏼

**Comment by thorstenwagner** [comment]
I will have alook! Thanks for letting me know.

**Comment by thorstenwagner** [comment]
Done :-)
