### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [MPI-Dortmund/napari-boxmanager#50]
Hello team!

While working on https://github.com/conda-forge/napari-boxmanager-feedstock/pull/12 we found a PyQt5 import.

See https://github.com/MPI-Dortmund/napari-boxmanager/blob/dd95166e0b685e9820c9f66604bc8cdf5feb5c3a/src/box_manager/_tests/test_organizelayer.py#L13

`from PyQt5.QtWidgets import QComboBox`

---

The plugin documentation for napari has a set of best practices for developers, which includes a clause recommending not to depend directly on PyQt5 or PySide2 to allow end-users to choose their bindings freely. [More details here](https://napari.org/stable/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies).

Even if it is a test, it would be good to use qtpy, to avoid accidentally adding a direct dependency on PyQt5.

Cheers! 🚀

**Comment by thorstenwagner** [comment]
Stupid me should have read better. Will fix it tomorrow...

**Comment by goanpeca** [comment]
Hi @thorstenwagner. While working on this https://github.com/conda-forge/napari-boxmanager-feedstock/pull/13 

 it seems pyqt5 was included as a dependency on the recent version
