### ISSUE TITLE
Error exporting particle layer to .cbox

### ISSUE THREAD

**Issue by flng000** [MPI-Dortmund/napari-boxmanager#59]
Hi there,

I tried using the napari boxmanager to create training data later required for crYOLO on one of my own tomograms (.mrc format). I followed the tutorial for crYOLO but napari always throws the following error when I try to save my particle layer:

AxisError: axis 1 is out of bounds for array of dimension 1

So far, I've tried the installation recommended for crYOLO as well as the standalone version of napari + boxmanager.
What is the cause of this or how can I prevent this from happening? Thank you for the help and all the best,

Felix

**Comment by thorstenwagner** [comment]
Hi Felix,

I tried to reproduce this issue but I can't. 

I opened an abitary tomo, created a particle layer, clicked on a few slices and saved it to disk (Organize Layer -> Save to dir). That worked nicely. Did you do anything different?

Have you installed the latest version of the boxmanager?  You can check it under Plugins -> Install / Uninstall 

Best,
Thorsten

**Comment by flng000** [comment]
Hi Thorsten,

Thank you for the fast response! I've tried with multiple tomograms now and run into the same issue. My boxmanager version is 0.4.7 which should be the most recent. Maybe my installation is messed-up (numpy?)

**Comment by flng000** [comment]
Hi Thorsten,

Exactly! Open File > .mrc tomogram > create particle layer > link layers > pick some particles and finally try to save.
So far, I have tried multiple tomograms but none worked. Also, I reinstalled everything into a fresh conda but this also didn't resolve the issue.

**Comment by flng000** [comment]
[cid:ce2377aa-2454-4cc8-af60-8a3b84b2c85a]

Looks the same for most settings

__________________________________________________

Dr. Felix Lange

Research Group Mitochondrial Structure and Dynamics

Max Planck Institute for Multidisciplinary Sciences
Dept. of NanoBiophotonics
Am Fassberg 11
37077 Göttingen, Germany
Tel.: 0551-201-2593
eMail: ***@***.***


________________________________
Von: Thorsten Wagner ***@***.***>
Gesendet: Donnerstag, 30. November 2023 11:39:57
An: MPI-Dortmund/napari-boxmanager
Cc: Lange, Felix; Author
Betreff: Re: [MPI-Dortmund/napari-boxmanager] Error exporting particle layer to .cbox (Issue #59)


I also made a fresh installation to see if something odd. But it works. Can you show me Help -> Napari Info

This is mine:
image.png (view on web)<https://github.com/MPI-Dortmund/napari-boxmanager/assets/1113977/f125e5f4-ad9f-4f0c-a70b-538f2aa24af8>

**Comment by thorstenwagner** [comment]
Hm, can we quickly have a video chat and you show me whats going on?

**Comment by flng000** [comment]
For anyone that runs in the same issue like me, here is the solution:

My system (for reasons I do not know by now) kept installing napari version 0.4.18. After the installation of napari use the command:

_pip install napari==0.4.17_

then proceed with the installation of napari_boxmanager

which solved the issue for me. Thank you again Thorsten for your time and help!!

**Comment by mstabrin** [comment]
Hello, maybe I have another idea...

Could you activate one of the broken environments and try the following:
`python -c 'import napari; print(napari.__file__)'`
